package GUI;

import Estructuras.Lista;
import Helpers.MouseL;
import Principal.Grafo;
import static Principal.Grafo.crearGrafo;
import static Principal.Grafo.generarIteraciones;
import Principal.Nodo;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.event.MouseWheelListener;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Raul
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    Grafo g;
    Graphics panelg;
    int it = 0;
    StringBuilder sb = new StringBuilder();
    String texto = "Iteración #";

    public Frame() {
        initComponents();
        this.setLocationRelativeTo(null);
        panelg = panelDraw.getGraphics();
        /*
        MouseL ml = new MouseL();
        this.addMouseListener(ml);
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDraw = new javax.swing.JPanel();
        itera = new javax.swing.JTextField();
        Anterior = new javax.swing.JButton();
        Crear = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDraw.setOpaque(false);

        javax.swing.GroupLayout panelDrawLayout = new javax.swing.GroupLayout(panelDraw);
        panelDraw.setLayout(panelDrawLayout);
        panelDrawLayout.setHorizontalGroup(
            panelDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        panelDrawLayout.setVerticalGroup(
            panelDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(panelDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 1070, 510));

        itera.setBackground(new java.awt.Color(0, 34, 25));
        itera.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        itera.setForeground(new java.awt.Color(255, 255, 255));
        itera.setBorder(null);
        itera.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        itera.setFocusable(false);
        itera.setOpaque(false);
        itera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iteraActionPerformed(evt);
            }
        });
        getContentPane().add(itera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 20));

        Anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/atras.png"))); // NOI18N
        Anterior.setBorderPainted(false);
        Anterior.setContentAreaFilled(false);
        Anterior.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(Anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 50, 90));

        Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/generar.png"))); // NOI18N
        Crear.setBorderPainted(false);
        Crear.setContentAreaFilled(false);
        Crear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        getContentPane().add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, 90, 90));

        Siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/adelante.png"))); // NOI18N
        Siguiente.setBorder(null);
        Siguiente.setBorderPainted(false);
        Siguiente.setContentAreaFilled(false);
        Siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 580, 40, 90));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/mascarilla.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 70, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/sinmascarilla.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 60, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/random.png"))); // NOI18N
        jButton3.setToolTipText("");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, -1, 60));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/play.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 580, -1, 90));

        Salir.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 0, 0));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/boton-salir-a-la-aplicacion.png"))); // NOI18N
        Salir.setText("Salir");
        Salir.setBorder(null);
        Salir.setBorderPainted(false);
        Salir.setContentAreaFilled(false);
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/gui2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, 160, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        g = crearGrafo(10, 0.2f, 0);
        //Mientras el grafo que se crea no sea fuertemente conexo, no dejará de generarlos
        while (!g.isStronglyConnected()) {
            g = crearGrafo(10, 0.2f, 0);
        }
        it = 0;
        StringBuilder sb = new StringBuilder();
        sb.append(texto + String.valueOf(it));
        itera.setText(String.valueOf(sb));
        try {
            drawGrafo(g);
        } catch (InterruptedException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }

        generarIteraciones(g, panelDraw.getGraphics());
        g.checkMatriz();
        g.displayIteraciones();
        g.displayGrafo();
        g.displayMatriz();
    }//GEN-LAST:event_CrearActionPerformed

    private void AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorActionPerformed
        Lista<Nodo> n = g.getIteraciones().get(it);
        for (Nodo nodo : g.getNodos()) {
            if (n.contains(nodo)) {
                nodo.setInfeccion(false);
                nodo.draw(panelg);
            }
        }
        if (it > 0) {
            it--;
        }
        StringBuilder sb = new StringBuilder();
        sb.append(texto + String.valueOf(it));
        itera.setText(String.valueOf(sb));
    }//GEN-LAST:event_AnteriorActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        if (it < g.getIteraciones().size() - 1) {
            it++;
        }
        StringBuilder sb = new StringBuilder();
        sb.append(texto + String.valueOf(it));
        itera.setText(String.valueOf(sb));
        Lista<Nodo> n = g.getIteraciones().get(it);
        for (Nodo nodo : n) {
            nodo.setInfeccion(true);
            nodo.draw(panelg);
        }
        System.out.println(it);
        System.out.println(g.getIteraciones().size());
    }//GEN-LAST:event_SiguienteActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void iteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iteraActionPerformed
        
    }//GEN-LAST:event_iteraActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        while (it < g.getIteraciones().size() - 1) {
            it++;
            Lista<Nodo> n = g.getIteraciones().get(it);
            for (Nodo nodo : n) {
                nodo.setInfeccion(true);
                nodo.draw(panelg);
            }
            try {
                TimeUnit.SECONDS.sleep(1);
            } catch (InterruptedException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    public void drawGrafo(Grafo gr) throws InterruptedException {
        panelDraw.getGraphics().clearRect(0, 0, panelDraw.getWidth(), panelDraw.getHeight());
        panelDraw.getGraphics().fillRect(0, 0, panelDraw.getWidth(), panelDraw.getHeight());
        gr.draw(panelDraw.getGraphics());

        /*
        int i = 0;
        while (i < gr.getNodos().size()) {
            TimeUnit.MILLISECONDS.sleep(25);
            g.drawRect(30 + i * 100, panel.getHeight() / 2, 30, 30);
            g.drawString(String.valueOf(i), 30+i*100, panel.getHeight()/2);
            i++;
        }
         */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior;
    private javax.swing.JButton Crear;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Siguiente;
    private javax.swing.JTextField itera;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelDraw;
    // End of variables declaration//GEN-END:variables
}
